/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.visao;

import br.edu.ifpr.paranavai.armarios.controle.LoginControlador;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author teren
 */
public class EditorLoginBibliotecaUI extends javax.swing.JFrame {

    /**
     * Creates new form AuthEditorUI
     */
    public EditorLoginBibliotecaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTextField2 = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        lblResposta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("E-mail");

        JTextField1.setForeground(new java.awt.Color(153, 153, 153));
        JTextField1.setText("Insira o e-mail");
        JTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTextField1FocusLost(evt);
            }
        });
        JTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextField1MouseClicked(evt);
            }
        });
        JTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");

        JTextField2.setForeground(new java.awt.Color(153, 153, 153));
        JTextField2.setText("senha");
        JTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTextField2FocusLost(evt);
            }
        });
        JTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField2ActionPerformed(evt);
            }
        });

        Login.setText("Emprestimo de Chave");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        lblResposta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Devolução");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(JTextField2))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblResposta)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField1ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_JTextField1ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        LoginControlador controle = new LoginControlador();
        String email = this.JTextField1.getText();
        String senha = String.copyValueOf(this.JTextField2.getPassword());
        String resposta = controle.verifica(email, senha); 
        System.out.println(resposta);
        lblResposta.setText(resposta);
        if (resposta.equals("Sucesso no login!")){
        new TelaDeEmprestimo().setVisible(true);
        this.dispose();
        }
    
    }//GEN-LAST:event_LoginActionPerformed

    private void JTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField2ActionPerformed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginControlador controle = new LoginControlador();
        String email = this.JTextField1.getText();
        String senha = String.copyValueOf(this.JTextField2.getPassword());
        String resposta = controle.verifica(email, senha); 
        System.out.println(resposta);
        lblResposta.setText(resposta);
        if (resposta.equals("Sucesso no login!")){
        new TelaDeDevolucao().setVisible(true);
        this.dispose();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextField1FocusGained
        if(JTextField1.getText().equals("Insira o e-mail"))
        {
            JTextField1.setText("");
            JTextField1.setForeground(new Color(0,0,0));
        }       
    }//GEN-LAST:event_JTextField1FocusGained

    private void JTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField1MouseClicked

    private void JTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextField1FocusLost
        if(JTextField1.getText().equals(""))
        {
            JTextField1.setText("Insira o e-mail");
            JTextField1.setForeground(new Color(0,0,0));
        } // TODO add your handling code here:
    }//GEN-LAST:event_JTextField1FocusLost

    private void JTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextField2FocusGained
        if(JTextField2.getText().equals("senha"))
        {
            JTextField2.setText("");
            JTextField2.setForeground(new Color(0,0,0));
        }  // TODO add your handling code here:
    }//GEN-LAST:event_JTextField2FocusGained

    private void JTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextField2FocusLost
        if(JTextField2.getText().equals(""))
        {
            JTextField2.setText("senha");
            JTextField2.setForeground(new Color(0,0,0));
        } // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorLoginBibliotecaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorLoginBibliotecaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorLoginBibliotecaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorLoginBibliotecaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorLoginBibliotecaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField1;
    private javax.swing.JPasswordField JTextField2;
    private javax.swing.JButton Login;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResposta;
    // End of variables declaration//GEN-END:variables
}
